In [10]:
# Import all the required libraries
import pandas as pd
import selenium
from selenium import webdriver
import time
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
import requests

In [11]:
# Activating the chrome browser
driver=webdriver.Chrome("chromedriver.exe")

In [12]:
# Opening the homepage of cartrader
url= "https://www.cartrade.com/"
driver.get(url)

# Locating search bar
click_btn=driver.find_element_by_xpath('//div[@class="red_mdl_mnu"]/ul/li')
click_btn.click()

# do click using id function
close_btn=driver.find_element_by_id("citybandclose")
close_btn.click()

In [3]:
#creating the empty urls list
urls=[]

# for scrapping the car url
for page in range(218):
    time.sleep(3)
    
    for i in driver.find_elements_by_xpath("//h2[@class='h2heading truncate']/a"):
        urls.append(i.get_attribute('href'))
    time.sleep(5)
    
    # do clicking on next button
    try:
        next_btn=driver.find_element_by_xpath("//li[@class='next']")
        next_btn.click()
    except:
        break

In [13]:
#creating the empty urls list
brand=[]
model=[]
variant=[]
manufacturing=[]
year=[]
driven_km=[]
fuel=[]
owners_number=[]
location=[]
price=[]

# scrapping the required data from url
for i in urls:
    driver.get(i)
    time.sleep(5)
    
    # for scrapping the brand name
    try:
        Brand=driver.find_element_by_xpath("//div[@class='breadcrumbs btmMrg']/ul/li[4]/a/span")
        brand.append(Brand.text)
    except NoSuchElementException:
        brand.append('-')
        
    # for scrapping the model name
    try:
        Model=driver.find_element_by_xpath("//div[@class='breadcrumbs btmMrg']/ul/li[5]/a/span")
        model.append(Model.text)
    except NoSuchElementException:
        model.append('-')
    
    # for scrapping the location 
    try:
        Location=driver.find_element_by_xpath("//table[@class='v_table']/tbody/tr[1]/td[2]")
        location.append(Location.text)
    except NoSuchElementException:
        location.append('-')
    
    try:
        Year=driver.find_element_by_xpath("//table[@class='v_table']/tbody/tr[8]/td[2]")
        year.append(Year.text)
    except NoSuchElementException:
        year.append('-')
    
    # for scrapping the driven_km
    try:
        km=driver.find_element_by_xpath("//table[@class='v_table']/tbody/tr[3]/td[2]")
        driven_km.append(km.text)
    except NoSuchElementException:
        driven_km.append('-')
    
    # for scrapping the fuel
    try:
        Fuel=driver.find_element_by_xpath("//table[@class='v_table']/tbody/tr[2]/td[2]")
        fuel.append(Fuel.text)
    except NoSuchElementException:
        fuel.append('-')
    
    # for scrapping the owner_number
    try:
        owner=driver.find_element_by_xpath("//table[@class='v_table']/tbody/tr[5]/td[2]")
        owners_number.append(owner.text)
    except NoSuchElementException:
        owners_number.append('-')
    
    # for scrapping the Price
    try:
        Price=driver.find_element_by_xpath("//div[@class='v_details']/div/div[1]/div[1]/span[2]")
        price.append(Price.text)
    except NoSuchElementException:
        price.append('-')

In [44]:
# creating the dataframe from the scraped data
df=pd.DataFrame({"Brand":brand,"Model":model,"Location":location,"Year":year,"Driven_km":driven_km,"Fuel":fuel,
                 "Owners_number":owners_number,"Price":price})
df

,Brand,Model,Location,Year,Driven_km,Fuel,Owners_number,Price
0,Toyota,Innova,Bangalore,2019,"14,113 Kms",Diesel,First,23.25 Lakh
1,Maruti Suzuki,Wagon R,Hyderabad,2015,"50,258 Kms",Petrol,First,4.4 Lakh
2,Mercedes-Benz,S-Class,Mumbai,2011,"51,086 Kms",Diesel,First,25 Lakh
3,Maruti Suzuki,Alto 800,Delhi,2018,"34,000 Kms",Petrol,First,3.1 Lakh
4,Volkswagen,Vento,Mumbai,2016,"45,259 Kms",Petrol,First,6.95 Lakh
...,...,...,...,...,...,...,...,...
5234,Mercedes-Benz,E-Class,Delhi,2018,"38,200 Kms",Diesel,First,47 Lakh
5235,Mercedes-Benz,CLA,Delhi,2017,"35,600 Kms",Diesel,Second,27 Lakh
5236,-,-,-,-,-,-,-,-
5237,Mercedes-Benz,E-Class,Delhi,2013,"95,200 Kms",Diesel,First,16.5 Lakh
5238,Hyundai,Eon,Mumbai,2018,"25,000 Kms",Petrol,First,3.2 Lakh

In [25]:
# Converting dataframe into excel file and storing it on desktop.
df.to_excel("C:\\Users\\PRIYA\\Cars_price.xlsx")